requires 'Algorithm::BloomFilter' => '0.02';
requires 'File::Slurp';
requires 'Firefox::Marionette'    => '0.66';
requires 'HTML::ExtractContent';
requires 'IO::Socket::SSL'        => '2.060';
requires 'JSON';
requires 'MCE::Loop';
requires 'Mojo::UserAgent';
requires 'Moo';
requires 'Regexp::Trie';
requires 'Text::Markdown';
requires 'Text::Markdown::Discount';
requires 'Try::Tiny';
requires 'Type::Tiny';
requires 'Types::URI';
requires 'URI';
