requires 'Algorithm::BloomFilter' => '0.02';
requires 'File::Slurp';
requires 'File::Next';
requires 'Firefox::Marionette'    => '0.66';
requires 'HTML::ExtractContent';
requires 'IO::Socket::SSL'        => '2.060';
requires 'JSON' => 4;
requires 'MCE::Loop';
requires 'Mojo::UserAgent';
requires 'Moo';
requires 'Regexp::Trie';
requires 'Text::Markdown';
requires 'Text::Markdown::Discount';
requires 'Time::Moment';
requires 'HTTP::Date';
requires 'Try::Tiny';
requires 'Type::Tiny';
requires 'Types::URI';
requires 'URI';
requires 'XML::FeedPP';
requires 'String::Trim';
requires 'PerlIO::via::gzip';
requires 'Chart::Plotly';
requires 'Net::Graphite';
requires 'JSON::Feed';
requires 'Text::Util::Chinese', '0.04';
requires 'Module::Functions';
requires 'WWW::Mechanize::Chrome';
requires 'WWW::Mechanize::PhantomJS';
